services:
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    container_name: plex-db
    restart: "no"
    ports:
      - "8080:8080"
    volumes:
      - sqld_data:/var/lib/sqld
    environment:
      TURSO_DATABASE_PATH: /var/lib/sqld

volumes:
  sqld_data: